version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: coffee-house-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coffee-house
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
